[tool.poetry]
name = "docker-images"
version = "1.0.0"
description = "Docker image manager"
authors = ["Janne Enberg <janne.enberg@lietu.net>"]
license = "BSD"
packages = [{ include = "docker_build", from = ".src" }]

[tool.poetry.dependencies]
python = "^3.6.1"
typer = "^0.6.1"
pytest = "^6.2.4"
pydantic = "^1.8.2"
PyYAML = "^5.4.1"
loguru = "^0.5.3"

[tool.skjold]
report_only = false
sources = ["pyup", "gemnasium"]

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
build = "docker_build.main:build"
upload = "docker_build.main:upload"
list = "docker_build.main:list"
docker_username = "docker_build.main:docker_username"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
