tags:
  - ubuntu-python-nginx-node
  - ubuntu-python-nginx-node14
  - ubuntu20.04-python-nginx-node
  - ubuntu20.04-python-nginx-node14
  - lts-python-nginx-node
  - lts-python-nginx-node14
  - ubuntu-python3.9-nginx-node
  - ubuntu-python3.9-nginx-node14
  - poetry1.2.0-nginx-node
  - poetry1.2.0-nginx-node14
  - lts-poetry1.2.0-nginx-node
  - lts-poetry1.2.0-nginx-node14
  - ubuntu-python-poetry1.2.0-nginx-node
  - ubuntu-python-poetry1.2.0-nginx-node14
  - ubuntu-python3.9-poetry1.2.0-nginx-node
  - ubuntu-python3.9-poetry1.2.0-nginx-node14
  - ubuntu20.04-python-poetry1.2.0-nginx-node
  - ubuntu20.04-python-poetry1.2.0-nginx-node14
  - ubuntu20.04-python3.9-poetry1.2.0-nginx-node
  - ubuntu20.04-python3.9-poetry1.2.0-nginx-node14
