tags:
  - ubuntu-python-nginx
  - ubuntu20.04-python-nginx
  - lts-python-nginx
  - ubuntu-python3.9-nginx
  - poetry1.2.0-nginx
  - lts-poetry1.2.0-nginx
  - ubuntu-python-poetry1.2.0-nginx
  - ubuntu-python3.9-poetry1.2.0-nginx
  - ubuntu20.04-python-poetry1.2.0-nginx
  - ubuntu20.04-python3.9-poetry1.2.0-nginx
