tags:
  - ubuntu-pyston
  - ubuntu20.04-pyston
  - lts-pyston
  - ubuntu-pyston2.2
  - pyston-poetry1.2.2
  - lts-pyston-poetry1.2.2
  - ubuntu-pyston-poetry1.2.2
  - ubuntu-pyston2.2-poetry1.2.2
  - ubuntu20.04-pyston-poetry1.2.2
  - ubuntu20.04-pyston2.2-poetry1.2.2
