tags:
  - latest
  - ubuntu-python
  - ubuntu20.04-python
  - lts-python
  - ubuntu-python3.9
  - poetry1.2.0
  - lts-poetry1.2.0
  - ubuntu-python-poetry1.2.0
  - ubuntu-python3.9-poetry1.2.0
  - ubuntu20.04-python-poetry1.2.0
  - ubuntu20.04-python3.9-poetry1.2.0
