tags:
  - ubuntu20.04-python
  - ubuntu-python3.9
  - poetry1.8.2
  - lts-poetry1.8.2
  - ubuntu-python-poetry1.8.2
  - ubuntu-python3.9-poetry1.8.2
  - ubuntu20.04-python-poetry1.8.2
  - ubuntu20.04-python3.9-poetry1.8.2
