name: Build and upload images to Docker hub

on:
  schedule:
    # First day of every month, you know, for automatic updates etc.
    - cron: "0 0 1 * *"
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build images
        run: poetry run build --parallel 8

      - name: Upload images
        if: success()
        run: |
          poetry run upload
